/**
 * Update Books Script: Add PDF URLs to existing books
 * 
 * This script:
 * 1. Reads pdf-upload-report.json (generated by upload-pdf-to-cos.ts)
 * 2. Matches PDF filenames with book titles in database
 * 3. Updates books.pdf_url field
 * 
 * Usage:
 *   npm run tsx script/update-books-pdf.ts
 */

import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { db } from '../server/db';
import { books } from '../shared/schema';
import { eq, sql, like } from 'drizzle-orm';

interface PDFUploadResult {
  filename: string;
  cosUrl: string;
  status: 'success' | 'skipped' | 'failed';
}

/**
 * Normalize string for fuzzy matching
 */
function normalize(str: string): string {
  return str
    .toLowerCase()
    .replace(/\.pdf$/i, '')
    .replace(/[^a-z0-9]+/g, '')
    .trim();
}

/**
 * Extract title from PDF filename
 * Handles formats like:
 * - "Title - Author.pdf"
 * - "Title_Author.pdf"
 * - "123. Title.pdf"
 */
function extractTitleFromFilename(filename: string): string {
  let title = filename.replace(/\.pdf$/i, '');
  
  // Remove leading numbers like "1234. " or "1234) "
  title = title.replace(/^\d+[\.\)]\s*/, '');
  
  // Try to remove author part (after last " - " or "_")
  const dashIndex = title.lastIndexOf(' - ');
  const underscoreIndex = title.lastIndexOf('_');
  const separatorIndex = Math.max(dashIndex, underscoreIndex);
  
  if (separatorIndex > 10) {
    title = title.substring(0, separatorIndex);
  }
  
  // Clean up
  title = title.replace(/_/g, ' ');
  title = title.replace(/\s+/g, ' ');
  
  return title.trim();
}

/**
 * Find best matching book for a PDF filename
 */
async function findMatchingBook(pdfFilename: string): Promise<any | null> {
  const extractedTitle = extractTitleFromFilename(pdfFilename);
  const normalizedPDF = normalize(pdfFilename);
  const normalizedTitle = normalize(extractedTitle);
  
  // Get all books
  const allBooks = await db.select().from(books);
  
  let bestMatch: any = null;
  let bestScore = 0;
  
  for (const book of allBooks) {
    if (!book.title) continue;
    
    const bookTitleNorm = normalize(book.title);
    const bookTitleFixNorm = book.titleFix ? normalize(book.titleFix) : '';
    
    // Score based on different matching strategies
    let score = 0;
    
    // Strategy 1: Exact normalized match
    if (bookTitleNorm === normalizedPDF || bookTitleFixNorm === normalizedPDF) {
      score = 100;
    }
    // Strategy 2: Normalized title match
    else if (bookTitleNorm === normalizedTitle || bookTitleFixNorm === normalizedTitle) {
      score = 95;
    }
    // Strategy 3: One contains the other (substring match)
    else if (normalizedPDF.includes(bookTitleNorm) || bookTitleNorm.includes(normalizedPDF)) {
      const shorter = normalizedPDF.length < bookTitleNorm.length ? normalizedPDF : bookTitleNorm;
      const longer = normalizedPDF.length < bookTitleNorm.length ? bookTitleNorm : normalizedPDF;
      const ratio = shorter.length / longer.length;
      score = ratio > 0.6 ? 80 * ratio : 0;
    }
    // Strategy 4: Check against titleFix
    else if (bookTitleFixNorm && (normalizedPDF.includes(bookTitleFixNorm) || bookTitleFixNorm.includes(normalizedPDF))) {
      const shorter = normalizedPDF.length < bookTitleFixNorm.length ? normalizedPDF : bookTitleFixNorm;
      const longer = normalizedPDF.length < bookTitleFixNorm.length ? bookTitleFixNorm : normalizedPDF;
      const ratio = shorter.length / longer.length;
      score = ratio > 0.6 ? 75 * ratio : 0;
    }
    
    if (score > bestScore) {
      bestScore = score;
      bestMatch = book;
    }
  }
  
  // Only return match if confidence is high enough (>60%)
  return bestScore > 60 ? { book: bestMatch, score: bestScore } : null;
}

async function updateBooksPDF() {
  console.log('📚 Updating books with PDF URLs...\n');
  
  // Read upload report
  const reportPath = path.join(process.cwd(), 'pdf-upload-report.json');
  
  if (!fs.existsSync(reportPath)) {
    console.error(`❌ Error: Report file not found: ${reportPath}`);
    console.log('\n💡 Run upload-pdf-to-cos.ts first to generate the report.\n');
    process.exit(1);
  }
  
  const report: PDFUploadResult[] = JSON.parse(fs.readFileSync(reportPath, 'utf-8'));
  const successfulUploads = report.filter(r => r.status === 'success' || r.status === 'skipped');
  
  console.log(`📊 Processing ${successfulUploads.length} PDF files...\n`);
  
  let updatedCount = 0;
  let notFoundCount = 0;
  let skippedCount = 0;
  
  const results: any[] = [];
  
  for (const pdf of successfulUploads) {
    const match = await findMatchingBook(pdf.filename);
    
    if (!match) {
      console.log(`❌ No match: ${pdf.filename}`);
      notFoundCount++;
      results.push({
        filename: pdf.filename,
        status: 'no_match',
        reason: 'No matching book found in database',
      });
      continue;
    }
    
    const { book, score } = match;
    
    // Skip if book already has PDF URL
    if (book.pdfUrl) {
      console.log(`⏭️  Skipped: "${book.title}" (already has PDF)`);
      skippedCount++;
      results.push({
        filename: pdf.filename,
        bookTitle: book.title,
        status: 'skipped',
        reason: 'Already has PDF URL',
      });
      continue;
    }
    
    // Update book
    await db
      .update(books)
      .set({ pdfUrl: pdf.cosUrl })
      .where(eq(books.id, book.id));
    
    console.log(`✅ Matched (${Math.round(score)}%): "${book.title}" ← ${pdf.filename}`);
    updatedCount++;
    
    results.push({
      filename: pdf.filename,
      bookId: book.id,
      bookTitle: book.title,
      pdfUrl: pdf.cosUrl,
      matchScore: Math.round(score),
      status: 'updated',
    });
  }
  
  // Save detailed results
  const resultsPath = path.join(process.cwd(), 'pdf-update-results.json');
  fs.writeFileSync(resultsPath, JSON.stringify(results, null, 2), 'utf-8');
  
  // Summary
  console.log('\n' + '='.repeat(60));
  console.log('📋 Update Summary');
  console.log('='.repeat(60));
  console.log(`✅ Updated:   ${updatedCount}`);
  console.log(`⏭️  Skipped:   ${skippedCount}`);
  console.log(`❌ Not found: ${notFoundCount}`);
  console.log(`📊 Total:     ${successfulUploads.length}`);
  console.log('='.repeat(60));
  console.log(`\n📄 Detailed results saved: ${resultsPath}\n`);
  
  // Show books that couldn't be matched
  if (notFoundCount > 0) {
    console.log('\n❌ PDFs without matching books:');
    results
      .filter(r => r.status === 'no_match')
      .slice(0, 10)
      .forEach(r => {
        console.log(`   - ${r.filename}`);
      });
    if (notFoundCount > 10) {
      console.log(`   ... and ${notFoundCount - 10} more\n`);
    }
    console.log('\n💡 Tips:');
    console.log('   - Ensure PDF filenames match book titles');
    console.log('   - Use format: "Title - Author.pdf" or "Title.pdf"');
    console.log('   - Check book titles in database');
  }
}

// Main execution
updateBooksPDF()
  .then(() => {
    console.log('✨ Update complete!\n');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Fatal error:', error);
    process.exit(1);
  });
